name: code-refactor

on:
    pull_request:
        branches:
            - master
            - develop
            - feature/*

jobs:
  code-refactor:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 1

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    - name: Install
      run: npm install
      env:
        CI: true

    - name: Run prettier
      run: npx prettier --write 'resources/**/*.{css,js,vue}' --config .prettierrc

    - name: Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Refactor code
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
